-- ---------------------------------------------------------------------------
-- supabase/bootstrap.sql
--
-- Idempotent setup for the booth lead-capture pipeline. Safe to re-run
-- against an existing instance — existing tables, columns, policies are
-- preserved. Run via Supabase Studio → SQL editor → New query → Run.
--
-- This file documents the full intended schema in one place. The migrations
-- folder records incremental changes (demographics columns, future fields,
-- etc.) and is what we'd apply via the Supabase CLI in a real CI pipeline.
-- For now, bootstrap.sql is the source of truth that operators can verify
-- their Supabase project against.
-- ---------------------------------------------------------------------------

-- ============================== TABLE =====================================

CREATE TABLE IF NOT EXISTS public.leads (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  captured_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- scan_id links the two writes per visitor: scan-start INSERT and
  -- form-submit UPSERT. UUID v4 generated client-side.
  scan_id          UUID,
  -- name / email / phone are nullable: filled at form submit, not at scan
  -- start. A row with these still NULL is a partial-funnel record.
  name             TEXT,
  email            TEXT,
  phone            TEXT,
  gender           TEXT,
  marketing_opt_in BOOLEAN NOT NULL DEFAULT false,
  body_type        TEXT,
  frame_size       TEXT,
  goal             TEXT,
  age_range        TEXT,
  height_range     TEXT,
  weight_range     TEXT,
  source           TEXT DEFAULT 'booth-fitscan'
);

-- Backfill onto a table that pre-dates this script.
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS scan_id          UUID;
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS frame_size       TEXT;
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS marketing_opt_in BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS body_type        TEXT;
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS goal             TEXT;
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS age_range        TEXT;
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS height_range     TEXT;
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS weight_range     TEXT;
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS source           TEXT DEFAULT 'booth-fitscan';

-- Drop legacy NOT NULLs on contact fields — initial-scan rows have these as NULL.
ALTER TABLE public.leads ALTER COLUMN name  DROP NOT NULL;
ALTER TABLE public.leads ALTER COLUMN email DROP NOT NULL;
ALTER TABLE public.leads ALTER COLUMN phone DROP NOT NULL;

-- Unique on scan_id (idempotent via CREATE UNIQUE INDEX IF NOT EXISTS).
CREATE UNIQUE INDEX IF NOT EXISTS leads_scan_id_uniq ON public.leads (scan_id);

-- ============================== CHECKS ====================================
-- Lightweight constraints so a typo in the client doesn't pollute analytics.
-- Comment out if you'd rather validate at the application layer.

ALTER TABLE public.leads
  DROP CONSTRAINT IF EXISTS leads_gender_chk,
  ADD CONSTRAINT leads_gender_chk
    CHECK (gender IS NULL OR gender IN ('male', 'female', 'other'));

ALTER TABLE public.leads
  DROP CONSTRAINT IF EXISTS leads_age_range_chk,
  ADD CONSTRAINT leads_age_range_chk
    CHECK (age_range IS NULL OR age_range IN ('18-24','25-34','35-44','45-54','55+'));

ALTER TABLE public.leads
  DROP CONSTRAINT IF EXISTS leads_height_range_chk,
  ADD CONSTRAINT leads_height_range_chk
    CHECK (height_range IS NULL OR height_range IN ('<165','165-175','175-185','185+'));

ALTER TABLE public.leads
  DROP CONSTRAINT IF EXISTS leads_weight_range_chk,
  ADD CONSTRAINT leads_weight_range_chk
    CHECK (weight_range IS NULL OR weight_range IN ('<60','60-75','75-90','90-105','105+'));

-- ============================== RLS =======================================
-- The anon key is shipped in the public JS bundle. RLS is what makes this
-- safe: anon can ONLY insert. It cannot read other rows, update, or delete.
-- The service-role key (server-only, never in the bundle) bypasses RLS for
-- exports / dashboards / etc.

ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon can insert leads" ON public.leads;
CREATE POLICY "anon can insert leads"
  ON public.leads
  FOR INSERT
  TO anon
  WITH CHECK (true);

-- The form-submit UPSERT also needs UPDATE permission for anon. Scoped
-- tightly: only rows that are still unfinalised (name IS NULL) AND fresh
-- (captured_at within the last 10 minutes). Once form submit sets name,
-- the row locks from anon edits. Practical security comes from scan_id
-- (UUIDv4, 122 bits) acting as a one-time bearer token.
DROP POLICY IF EXISTS "anon can update unfinalised leads" ON public.leads;
CREATE POLICY "anon can update unfinalised leads"
  ON public.leads
  FOR UPDATE
  TO anon
  USING (name IS NULL AND captured_at > now() - interval '10 minutes')
  WITH CHECK (true);

-- PostgREST upsert (on_conflict=scan_id + merge-duplicates) needs SELECT
-- to resolve conflicts. Same tight scope as UPDATE — visibility limited to
-- unfinalised rows in the last 10 minutes. After form submit, row hides.
DROP POLICY IF EXISTS "anon can select unfinalised leads" ON public.leads;
CREATE POLICY "anon can select unfinalised leads"
  ON public.leads
  FOR SELECT
  TO anon
  USING (name IS NULL AND captured_at > now() - interval '10 minutes');

-- ============================== INDEXES ===================================
-- Helpful for the marketing dashboard. Cheap to maintain at booth volumes.

CREATE INDEX IF NOT EXISTS leads_captured_at_idx     ON public.leads (captured_at DESC);
CREATE INDEX IF NOT EXISTS leads_marketing_idx       ON public.leads (marketing_opt_in) WHERE marketing_opt_in = true;
CREATE INDEX IF NOT EXISTS leads_email_lower_idx     ON public.leads (lower(email));

-- ============================== SANITY CHECK ==============================
-- Verify the policy is exactly what we expect. If this returns 0 rows the
-- anon insert won't work — re-run the policy block above.

-- SELECT polname, cmd, roles FROM pg_policies WHERE tablename = 'leads';
